services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:10000
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/code/api_system/resources/hackadisc-firebase-adminsdk-83jqv-d3156e8d2a.json
      - POSTGRESQL_DB_HOST=${POSTGRESQL_DB_HOST}
      - POSTGRESQL_DB_PORT=${POSTGRESQL_DB_PORT}
      - POSTGRESQL_DB_NAME=${POSTGRESQL_DB_NAME}
      - POSTGRESQL_DB_USER=${POSTGRESQL_DB_USER}
      - POSTGRESQL_DB_PASSWD=${POSTGRESQL_DB_PASSWD}

    ports:
      - "10000:10000"
