# Generated by Django 5.0.6 on 2024-06-21 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_system', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('area_id', models.IntegerField(default=-1)),
                ('role', models.IntegerField(choices=[(1, 'Admin Pignus'), (2, 'Admin Company'), (3, 'Admin Area')], default=3)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_system.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
