# Generated by Django 5.0.6 on 2024-06-21 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('is_multi_main', models.BooleanField(default=False)),
                ('main_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_system.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_system.company')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('category', models.IntegerField(choices=[(1, 'Course'), (2, 'Training'), (3, 'Speech')])),
                ('competence', models.IntegerField(choices=[(1, 'Adaptability'), (2, 'Conduct'), (3, 'Dynamism'), (4, 'Effectiveness'), (5, 'Initiative'), (6, 'Pressure')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_system.company')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_id', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_system.intervention')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('area_id', models.IntegerField()),
                ('area_name', models.CharField(max_length=100)),
                ('post_id', models.IntegerField()),
                ('post_name', models.CharField(max_length=100)),
                ('state', models.IntegerField(choices=[(0, 'Not Evaluated'), (1, 'Evaluated'), (2, 'In Intervention'), (3, 'Intervened')], default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_system.company')),
            ],
        ),
        migrations.CreateModel(
            name='InterventionParticipant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_system.intervention')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_participants', to='api_system.worker')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('adaptability_to_change', models.FloatField()),
                ('safe_conduct', models.FloatField()),
                ('dynamism_energy', models.FloatField()),
                ('personal_effectiveness', models.FloatField()),
                ('initiative', models.FloatField()),
                ('working_under_pressure', models.FloatField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_system.worker')),
            ],
        ),
    ]
