# Generated by Django 5.0.6 on 2024-06-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='category',
            field=models.IntegerField(choices=[(1, 'Curso'), (2, 'Capacitación'), (3, 'Charla')]),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='competence',
            field=models.IntegerField(choices=[(1, 'Adaptabilidad'), (2, 'Trabajo bajo presión'), (3, 'Iniciativa'), (4, 'Dinamismo y energía'), (5, 'Conducta segura'), (6, 'Efectividad')]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='state',
            field=models.IntegerField(choices=[(0, 'No evaluado'), (1, 'Evaluado'), (2, 'En intervención'), (3, 'Intervenido')], default=1),
        ),
    ]
