# Generated by Django 5.0.6 on 2024-06-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(default='test@pignus.cl', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='rut',
            field=models.CharField(default='1111-1', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
