# Generated by Django 5.0.6 on 2024-06-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_system', '0002_alter_intervention_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
