# Generated by Django 5.0.6 on 2024-06-20 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_system', '0002_worker_email_worker_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='main_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_system.company'),
        ),
    ]
