# Generated by Django 5.0.6 on 2024-06-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_system', '0004_alter_worker_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
