# Generated by Django 5.0.6 on 2024-06-20 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_system', '0004_alter_worker_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_id', models.TextField()),
                ('invervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_system.intervention')),
            ],
        ),
    ]
