# Generated by Django 5.0.6 on 2024-06-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_system', '0005_interventiondocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interventiondocument',
            old_name='invervention',
            new_name='intervention',
        ),
    ]
