# Generated by Django 5.0.6 on 2024-06-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_system', '0006_rename_invervention_interventiondocument_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventiondocument',
            name='name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
